### ISSUE TITLE
Looking for Mentors - August, 2015

### ISSUE THREAD

**Issue by thejones** [nodeschool/anchorage#1]
Our first event will be August, 2015. The date is TBD as well as the place but this will be a good place to track any interest in becoming a mentor for this event.

**Comment by simonv3** [comment]
I'm interested, but it would depend on when, and whether I can get transport down from Denali for the period of time.

**Comment by thejones** [comment]
@simonv3 Is there a specific date that works for you? I am targeting between the 4th - 18th of August.

**Comment by simonv3** [comment]
@thejones I have family visiting from the 9th - 22nd, and I work during the week, so the best time in that time frame for me would be the weekend 7 - 9th.

Edit: I also definitely don't want to be the defining factor, because I'll only really know closer to the date whether I can come at all (rides etc).

**Comment by mikehumphrey** [comment]
Sign Me Up!!! I would love to participate in the planning of future schools and teaching aspects as needed.

**Comment by thejones** [comment]
@mikehumphrey does the 8th or 9th work with your schedule?

**Comment by mikehumphrey** [comment]
Yeah I think that can totally work either day.  What are the times you are thinking?

**Comment by thejones** [comment]
Saturday afternoon from 1-4 PM?

**Comment by mikehumphrey** [comment]
Yeah that would work for me.  Have you secured a location or have some ideas of a good place? If we need a temporary Wifi Hotspot for an event I have a contact at Verizon that I can work with.

**Comment by thejones** [comment]
@mikehumphrey we can do this event at RDI (3rd floor).

**Comment by thejones** [comment]
Event has happened. Closing this.
