### ISSUE TITLE
Call for mentors - End of February 

### ISSUE THREAD

**Issue by thejones** [nodeschool/anchorage#2]
The next event is right around the corner. I am looking for people interested in helping as well as suggestions for a date. 

Saturday again or weeknight? 

We are also going to try a new format of live code/instruction with a tangible end result that can be pushed to a host on the www. 

Boom! 

@mikehumphrey

**Comment by NigelKibodeaux** [comment]
Did this already happen?

**Comment by mikehumphrey** [comment]
Nigel, No not yet... We are working towards scheduling our next event if you are interested in attending or being a mentor.  We will keep you posted.  Mike HumphreyOn Dec 29, 2015, at 07:36 AM, Nigel Kibodeaux notifications@github.com wrote:Did this already happen?—Reply to this email directly or view it on GitHub.

**Comment by thejones** [comment]
@NigelKibodeaux @mikehumphrey End of January? I can do the last two weekends either the 23rd or 30th. If this sounds appealing I will pursue finding a location. Boardroom, Annex (Palmer), RDI, @NigelKibodeaux house, etc.

**Comment by NigelKibodeaux** [comment]
I'm going to be out of town between those 2 weekends. Could the first
weekend in February work?  Also, I don't even know what this thing is
really! But it sounds interesting.

**Comment by thejones** [comment]
As of today we are targeting February 27 or 28. We will find a venue and then lock down the date and start to promote. For this event we might go slightly north and try Palmer. 

@NigelKibodeaux NodeSchool is an event to try and promote Node/JS to anybody that is interested in learning more. With your level of experience it would be great to have you come out and help show people how to node.

**Comment by NigelKibodeaux** [comment]
Cool, I'll be in town then
