### ISSUE TITLE
September 17, 2016 - Hack on something!

### ISSUE THREAD

**Issue by thejones** [nodeschool/anchorage#4]
September 17, 2016, will be dedicated to hacking away on a personal project. As a group, we can work through problems (ideas or code related).

**Comment by thejones** [comment]
@mansuleman I changed the date on this as I injured my back. New date is Sept 17. This is going to be a beginner-friendly workshop to go over problems, etc. It is also a great time for everybody to set aside a few hours to get something done and have a coffee.

**Comment by alaskanloops** [comment]
Awesome!! Where is it going to be?

**Comment by thejones** [comment]
Just finalized this at lunch today! 

I was able to get the Brayton Kaladi Community room, but please note the time change. I had to move it to 1:30 - 3:30 PM.

**Comment by alaskanloops** [comment]
Sweet deal!  I was surprised to find a node school event happening in town.  Was just showing nodeschool to a coworker wanting to learn node, and spotted it.  I'll try to make it!
